MaxCut, Graph Partitioning, and Dirac-3 Quick Start Tutorial Updates
qci-enablement/qci-data pull request #44
Opened 2024-04-17 14:09 UTC by uchukwu

Tutorial updates for maxcut, graph partitioning, and Dirac-3 quick start. Updates reflect code change in qci-client v4.0. Few changes that occur:

1. Change of `sampler_type` to `device_type` and `nsamples` to `num_samples` in `job_params` of `qci_client.build_job_body`.
2. Removal of the redundant `job_type` in `qci_client.process_job`.
3. Simplification of response object; simply retrieve `results` of response dict via `response['results']`

**NOTE**: In Dirac-3 Quick Start tutorial, I wasn't able to replicate degeneracy in last example. I've made 3-5 attempts to do so to no avail. Let me know how we should proceed with this.

2024-04-17 14:36 UTC, uchukwu commented
Added a python helper file and image file that's suppose to be generated in the graph partitioning notebook tutorial

2024-04-17 15:39 UTC, RussellHuffman approved these changes
I did a copy review of the three tutorials and pushed those to the branch, so I am approving this PR from that perspective.

2024-04-17 20:42 UTC, thisisaus requested changes
Only request it to run the qudit tutorial again to get more variety in the degeneracy section.

2024-04-17 20:42 UTC, thisisaus commented on learn/tutorials-and-use-cases/Qudit-Tutorial.ipynb
The degeneracy demonstration shows the same solution 10 times. I've had this happen before. It would be better to show some of the other solutions as well. See if running it again gives more variety.

2024-04-17 22:01 UTC, uchukwu commented on learn/tutorials-and-use-cases/Qudit-Tutorial.ipynb
Ok, will do that

2024-04-18 14:58 UTC, uchukwu commented
@thisisaus ready for your follow-up review

2024-04-19 21:17 UTC, thisisaus approved these changes

2024-04-19 23:47 UTC, merged